# Generated by Django 3.1.7 on 2021-04-14 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=60)),
                ('hidden', models.BooleanField(default=False)),
                ('rangesHidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('scenarioId', models.CharField(max_length=60)),
                ('latitude', models.CharField(max_length=60)),
                ('longitude', models.CharField(max_length=60)),
                ('range0', models.CharField(max_length=60)),
                ('frequency0', models.CharField(max_length=60)),
                ('range1', models.CharField(max_length=60)),
                ('frequency1', models.CharField(max_length=60)),
                ('range2', models.CharField(max_length=60)),
                ('frequency2', models.CharField(max_length=60)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site')),
            ],
        ),
    ]
